### ISSUE TITLE
Not existing Bug tracker URL

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_kopere_mobile#11]
Hello,
please update Bug tracker URL to the new GitHub URL:

![image](https://github.com/user-attachments/assets/fdb36e9f-d202-434e-aa7e-1ddf3515edc6)
![image](https://github.com/user-attachments/assets/fb3ca546-dd4a-4c80-ad6f-b549b6ccdfc0)

**Comment by eduardokraus** [comment]
Done
