### ISSUE TITLE
Modification to global $USER object found

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_kopere_mobile#8]
Hello,
I found global $USER object modification. Please consider an alternative implementation with session/cache or [Preferences API ](https://moodledev.io/docs/4.4/apis/core/preference)

![image](https://github.com/user-attachments/assets/ea5db63c-761d-4620-9388-480427dc46ad)
![image](https://github.com/user-attachments/assets/a2ae8ab3-eb15-4f55-8faf-2727934b6fe8)

**Comment by eduardokraus** [comment]
These values are temporary, stored only in the session, and are not saved in the database.

**Comment by volodymyrdovhan** [comment]
@eduardokraus is there a chance to move this to the $SESSION or use get/set_user_preferences() ?

**Comment by eduardokraus** [comment]
These values are temporary in this session, stored only in the session, and are not saved in the database.

**Comment by eduardokraus** [comment]
When the app opens any Moodle content in an iframe or inappbrowser, I need to identify if this navigation was initiated by the app itself. For this, I only need these variables during this specific session.

The variable local_kopere_mobile_preserve_page is necessary, for example, when the forum is opened in an iframe. I need to detect when the user leaves the forum and navigates to another component, allowing me to monitor page transitions within the same session.
